<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "portfolio_cs"
 *
 * Auto generated by Extension Builder 2019-01-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'PortfolioCasa',
    'description' => 'Portfolio',
    'category' => 'plugin',
    'author' => 'Julien VITTE, Louis Réjou, Arthur Cargnelli, Arthur Derichard, Sophie Candau',
    'author_email' => 'vitte.julien@gmail.com, lrejou@u-bordeaux.fr, arthur.cargnelli@etu.u-bordeaux.fr, aderichard@u-bordeaux.fr, scandau@u-bordeaux.fr',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
